#!/usr/bin/env groovy

@Library('shared-library@master')

pipeline {
  agent {
    docker {
      image 'mave'
      args '-v $HOME/.m2:/root/.m2'
    }
  }
  stages {
    stage ('maven build') {
      steps {
        script {
          sh 'mv clean install'
        }
      }
    }
    stage ('check logs'){
      steps {
        filterLogs ( 'WARNING', 1)
      }
    }
  }
}
