#!/usr/bin/env groovy

@Library('shared-library@master') _

pipeline {
  agent any
  }
  stages {
    stage ('maven build') {
      steps {
        script {
          sh 'mv clean install'
        }
      }
    }
    // stage ('check logs') {
    //   steps {
    //     filterLogs ( 'WARNING', 1)
    //   }
    // }
  }
}
